FUNCTION PARAMS AND RETURN VALUES

In [ ]:
#nomor 1

def penjumlahan(a,b):
    return a+b
def pengurangan(a,b):
    return a-b
def perkalian(a,b):
    return a*b
def pembagian(a,b):
    return a/b

while True:
    print('Silakan pilih menu:')
    print('1. Penjumlahan')
    print('2. Pengurangan')
    print('3. Perkalian')
    print('4. Pembagian')
    menu = int(input('Masukkan pilihan: '))

    if menu == 1:
        angka1 = int(input('Masukkan angka pertama: '))
        angka2 = int(input('Masukkan angka kedua: '))
        print('Hasil penjumlahan adalah ', penjumlahan(angka1,angka2))
    elif menu == 2:
        angka1 = int(input('Masukkan angka pertama: '))
        angka2 = int(input('Masukkan angka kedua: '))
        print('Hasil pengurangan adalah ', pengurangan(angka1,angka2))
    elif menu == 3:
        angka1 = int(input('Masukkan angka pertama: '))
        angka2 = int(input('Masukkan angka kedua: '))
        print('Hasil perkalian adalah ', perkalian(angka1,angka2))
    elif menu == 4:
        angka1 = int(input('Masukkan angka pertama: '))
        angka2 = int(input('Masukkan angka kedua: '))
        print('Hasil pembagian adalah ', pembagian(angka1,angka2))
    else:
        print('Menu invalid')
    
    mau_lagi = input('Masih ingin memilih (Y/T)?')

    if mau_lagi == 'T' or mau_lagi == 't':
        break

print('Terimakasih. Selamat datang kembali.')

In [2]:
#nomor 2

def cek_nilai(listku):
    if len(listku) == 0:
        return "List kosong. Tidak ada nilai terbesar atau terkecil."
    else:  
        terbesar = max(listku)
        terkecil = min(listku)
        print('Nilai terbesar dari list: ', terbesar)
        print('Nilai terbesar dari list: ', terkecil)
    
cek_nilai([3,44,5,22,90,0,4,37,88])

Nilai terbesar dari list:  90
Nilai terbesar dari list:  0


assignment numpy

In [42]:
import numpy as np

In [27]:
#nomor 1

array1 = np.array([
    [10,20,30],
    [5,10,20],
    [2,4,6]
])
print(array1)

[[10 20 30]
 [ 5 10 20]
 [ 2  4  6]]


In [40]:
#nomor 2

array2 = np.array([
    [[10,11,12], [13,14,15], [16,17,18]],
    [[20,21,22], [23,24,25], [26,27,28]],
    [[30,31,32], [33,34,35], [36,37,38]],
])
print(array2)

[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[20 21 22]
  [23 24 25]
  [26 27 28]]

 [[30 31 32]
  [33 34 35]
  [36 37 38]]]


In [41]:
#nomor 3

array3 = np.array([
    [['macbook',3,'25jt'], ['asus',15,'11jt'],['hp',6,'8jt']],
    [['iPhone',5,'13jt'],['Oppo',22,'5jt'],['Vivo',8,'4jt']]
])
print(array3)
print('dimensi: ', array3.ndim)
print('shape: ', array3.shape)

[[['macbook' '3' '25jt']
  ['asus' '15' '11jt']
  ['hp' '6' '8jt']]

 [['iPhone' '5' '13jt']
  ['Oppo' '22' '5jt']
  ['Vivo' '8' '4jt']]]
dimensi:  3
shape:  (2, 3, 3)


In [38]:
#nomor 4

array4 = np.array([
    ['Raka',21, 'Badung', 'Programmer'],
    ['Bayu',22, 'Denpasar', 'Web Developer'],
    ['Sri',18, 'Gianyar', 'Android Developer'],
    ['Dimas', 30, 'Bangli', 'Data Analyst']
])
print(array4)
print('shape: ', array4.shape) #ordo
print('dimensi: ', array4.ndim) #dimensi
print('size: ', array4.size) #banyak elemen


[['Raka' '21' 'Badung' 'Programmer']
 ['Bayu' '22' 'Denpasar' 'Web Developer']
 ['Sri' '18' 'Gianyar' 'Android Developer']
 ['Dimas' '30' 'Bangli' 'Data Analyst']]
shape:  (4, 4)
dimensi:  2
size:  16


assignment numpy - slicing and indexing

In [82]:
#array pertama

#nomor 1
array4 = np.array([
    ['Denis', 'Scrath', 8],
    ['Frank', 'Python', 18],
    ['Roger', 'Unity', 5]
])

#nomor 2
print('baris 1: ', array4[0])
print('baris 2: ', array4[1])
print('baris 3: ', array4[2])

#nomor 3
print()
print('kolom pertama dan kedua: ')
print(array4[0:,0:2])
print()
print('kolom 1: ', array4[:,0])
print('kolom 2: ', array4[:,1])

#nomor 4
print()
array4[0][1] = 'Roblox'
print('setelah ubah data: ')
print(array4)

baris 1:  ['Denis' 'Scrath' '8']
baris 2:  ['Frank' 'Python' '18']
baris 3:  ['Roger' 'Unity' '5']

kolom pertama dan kedua: 
[['Denis' 'Scrath']
 ['Frank' 'Python']
 ['Roger' 'Unity']]

kolom 1:  ['Denis' 'Frank' 'Roger']
kolom 2:  ['Scrath' 'Python' 'Unity']

setelah ubah data: 
[['Denis' 'Roblox' '8']
 ['Frank' 'Python' '18']
 ['Roger' 'Unity' '5']]


In [92]:
# array kedua

# nomor 1
array5 = np.array([
    ['Java', 'Richie', 60, 'C'],
    ['Python', 'Niels', 80, 'A'],
    ['R', 'Brie', 75, 'B']
])

#nomor 2
print('baris 1: ', array5[0])
print('baris 2: ', array5[1])
print('baris 3: ', array5[2])

#nomor 3
print()
print('kolom 1: ', array5[:,0])
print('kolom 2: ', array5[:,1])
print('kolom 3: ', array5[:,2])
print('kolom 4: ', array5[:,3])

# nomor 4
print()
print('data pada 2 baris pertama')
print(array5[0:2,])
print()
print('data pada 2 kolom terakhir')
print(array5[:,2:])
print()
print('data pada 2 baris pertama dan 2 kolom terakhir')
print(array5[0:2,2:])

baris 1:  ['Java' 'Richie' '60' 'C']
baris 2:  ['Python' 'Niels' '80' 'A']
baris 3:  ['R' 'Brie' '75' 'B']

kolom 1:  ['Java' 'Python' 'R']
kolom 2:  ['Richie' 'Niels' 'Brie']
kolom 3:  ['60' '80' '75']
kolom 4:  ['C' 'A' 'B']

data pada 2 baris pertama
[['Java' 'Richie' '60' 'C']
 ['Python' 'Niels' '80' 'A']]

data pada 2 kolom terakhir
[['60' 'C']
 ['80' 'A']
 ['75' 'B']]

data pada 2 baris pertama dan 2 kolom terakhir
[['60' 'C']
 ['80' 'A']]


In [89]:
# nomor 5
print()
array5[:,0] = 'DataAnalyst'
print('data pada kolom pertama diubah jadi DataAnalyst')
print(array5)

# nomor 6
print()
array5[2][2] = 90
print('ubah nilai 75 jadi 90')
print(array5)
print()
array5[2][3] = 'A+'
print('ubah nilai B jadi A+')
print(array5)


data pada kolom pertama diubah jadi DataAnalyst
[['DataAnalyst' 'Richie' '60' 'C']
 ['DataAnalyst' 'Niels' '80' 'A']
 ['DataAnalyst' 'Brie' '75' 'B']]

ubah nilai 75 jadi 90
[['DataAnalyst' 'Richie' '60' 'C']
 ['DataAnalyst' 'Niels' '80' 'A']
 ['DataAnalyst' 'Brie' '90' 'B']]

ubah nilai B jadi A+
[['DataAnalyst' 'Richie' '60' 'C']
 ['DataAnalyst' 'Niels' '80' 'A']
 ['DataAnalyst' 'Brie' '90' 'A+']]
