jenis fungsi

In [2]:
#function void

def tambah():
    a=10
    b=20
    print(a+b)

#function parameter adl function yang dapat menerima value di luar functionnya

def tambah(a,b):
    hasil = a+b
    print(hasil)

#function return 

def tambah(a,b):
    hasil = a+b
    return hasil

fungsi global

In [7]:
nilai = 100

def tambah():
    nilai = 200
    print(nilai)

tambah()
print(nilai)

200
100


In [ ]:
nilai = 100

def tambah():
    global nilai #untuk manggil nilai yang di luar fungsi
    nilai = 200 #ubah nilai
    print(nilai)

tambah()
print(nilai) #berubah nilainya krn function sudah dijalankan

200
200


In [8]:
nilai = 100

def tambah():
    global nilai 
    nilai = 200
    print(nilai)

print(nilai) #tetap yang awal karena functionnya belum dijalankan
tambah()

100
200


function recursive

In [ ]:
def test(n):
    if n == 0:
        return True # boleh return apapun asal ada returnnya
    
    print(n)
    test(n-1)

test(5)

5
4
3
2
1


In [ ]:
def test(n): #faktorial, mirip nested for atau nested yang lain
    if n == 0:
        return True
    else:
        return n * test(n-1)   

test(5)

120

tuple

In [12]:
test1 = [10,20,30] #list
test2 = {10,20,30} #set
#list dan set bisa diakses dan bisa diubah
test3 = (10,20,30) #tuple, tidak bisa diubah tapi tidak bisa diakses

args kwargs

In [13]:
# data yang disimpan pada args berupa tuple, tanda *
# kalau pada kwargs berupa dict, tanda **

In [14]:
def tampil(*a): # * menandakan args
    print(a)
    print(a[0])
    print(a[1])
    print(a[2])

tampil('satu', 'dua', 'tiga')


('satu', 'dua', 'tiga')
satu
dua
tiga


In [15]:
def tampil(*a): # * menandakan args
    print(a)
    for i in a: 
        print(i)

tampil('satu', 'dua', 'tiga')

('satu', 'dua', 'tiga')
satu
dua
tiga


In [16]:
def tampil2(**a): # ** menandakan kwargs
    print(a)

tampil2(nama ='emik', alamat='sukawati')

{'nama': 'emik', 'alamat': 'sukawati'}


In [17]:
def tampil2(**a): # ** menandakan kwargs
    print(a)
    for i in a.keys():
        print(a[i])

tampil2(nama ='emik', alamat='sukawati')

{'nama': 'emik', 'alamat': 'sukawati'}
emik
sukawati


NUMPY

In [18]:
#ingat kalau di vscode library tidak ada, harus diinstal dulu
#misal:  pip install numpy

In [19]:
import numpy as np

a = np.array([1,2,3,4]) #array 1 dimensi
print(a)
print(a[0])

[1 2 3 4]
1


In [20]:
#array 2 dimensi = array yang memiliki kumpulan aaray 1 D di dalamnya

b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]) #array 2 dimensi
print(b)
print(b[0])
print(b[0][2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
3


In [21]:
#3D

c = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
        [4,5,6]
    ]
])

print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
print(c[0])

[[1 2 3]
 [4 5 6]]


In [23]:
print(c[0][0])

[1 2 3]


In [24]:
print(c[0][0][2])

3


In [25]:
print(b.shape) #ordo
print(b.ndim) #dimensi
print(b.size) #banyak elemen

(3, 3)
2
9


indexing and slicing

In [29]:
d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(d[0:,:2]) #[baris awal sampai ke bawah, kolom awal sampai sblm kolom batas] 

[[1 2]
 [4 5]
 [7 8]]


In [ ]:
print(d[0:2,0:2]) #dari baris 0 sampai sblm baris 2, dari kolom 0 sampai sblm kolom 2

[[1 2]
 [4 5]]


In [31]:
print(d[0:,0:2]) #dari baris 0 sampai akhir, dari kolom 0 sampai sblm kolom 2

[[1 2]
 [4 5]
 [7 8]]


In [32]:
#mengganti data

d[0][1] = 100 #ganti baris indeks 0 dan kolom indeks 1 jadi 100
d

array([[  1, 100,   3],
       [  4,   5,   6],
       [  7,   8,   9]])